### ISSUE TITLE
User data is not written to plone 6

### ISSUE THREAD

**Issue by rogerborges** [collective/pas.plugins.ldap#117]
I installed the plugin, I was able to authenticate in LDAP but the data is not written to plone. 
When I click on user preferences: ERROR [pas.plugins.ldap:93][waitress-0] LDAPError in enumerateUsers. Also WARNING [Products.CMFPlone:99][waitress-3] Skipped user without principal object: rogerborges. 
Login as admin and don't have "rogerborges" user data in Plone.

Plone 6 with Volto
pas.plugins.ldap==1.8.2
Plone 6.0.0b2
Zope 5.6
Python 3.9.13

**Comment by rogerborges** [comment]
The problem is that it authenticates normally through ldap but does not store the user in the plone database (users in Plone)

**Comment by jensens** [comment]
It is not the idea to store the user in Plone. The user must not exist as a standard Plone user! 

Thus said, you can add additional user data that exists in Plone only (layered property sheets).
Depending on order the layers are defined in PAS even overriding of values is possible.
