### ISSUE TITLE
Credentials are logged

### ISSUE THREAD

**Issue by felix-ulonska** [collective/pas.plugins.ldap#124]
When the log level is debug, the credentials are logged into the log file. This is security problem. If possible, replace the password with ###.

**Comment by jensens** [comment]
This is by intend. The idea is to never log in production with level debug. However, if there is a real world scenario where this is a problem we can change it.

**Comment by felix-ulonska** [comment]
I am running a "not that critical" production deployment. I was informed that there were problems with logging in but I could not reproduce it, therefore I enabled debug log. This resulted me seeing user passwords. IMHO: Therefore it is best to add a big warning or just censor the passwords. Another idea would be to add an environment variable "INSECURE" which needs to be set for this behavior to happen.

**Comment by rnixx** [comment]
> just censor the passwords

+1

**Comment by mamoep** [comment]
Being able to extract user passwords by enabling debug logging poses a security risk. I propose a simple fix: #126
