### ISSUE TITLE
Icons in pas.plugins.ldap will not display

### ISSUE THREAD

**Issue by Cherry10** [collective/pas.plugins.ldap#14]
Hi,
in Plone 4.3.4 the icons  to configure (plus, minus, etc.)  the ldap group settings don't display correctly. So I can't add some object classes or other settings. I often reinstalled the plugin and yafowil but it don't works.
Is this plugin not compatible with the current Plone version? Have anybody an idea how I can add some object classes / attributes or how I can fix this display problem?

Thanks!
Best regards.

**Comment by rnixx** [comment]
probably re applying the generic setup profile for yafowil.plone solves your problem

**Comment by Cherry10** [comment]
Could you tell me which steps for reapplying are necessary? I have only reinstalled it about portal_quickinstaller.

**Comment by rnixx** [comment]
ZMI -> portal_setup -> import -> select yafowil.plone profile -> scroll down -> click import all steps

**Comment by Cherry10** [comment]
Hi, 
sorry, but it doesen't work. The icons will not display after reapplying the profile.

**Comment by rnixx** [comment]
please try latest yafowil.widget.array. The issue should be fixed
