### ISSUE TITLE
How to get group memberships to work?

### ISSUE THREAD

**Issue by CharString** [collective/pas.plugins.ldap#21]
I'm talking to an openldap server that has **posixAccount** and **posixGroup** objects.
Both Users and Groups appear in Plone, but I'm having a hard time getting the memberships to work.

There are 2 ways a posixAccount can be member of a posixGroup:
  - the posixAccount  can have a _gidNumber_ attribute that corresponds to the _gidNumber_ of a posixGroup
  - A posixGroup can have a _memberUid_ attribute that can have a list that correspond to _uid_'s of posixAccounts

How do I get this to work?

**Comment by rnixx** [comment]
Here is the test setup config for posix account and posix group support.
https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/testing/__init__.py#L564
There's also support for the ``memberOf`` overlay of openldap

**Comment by rnixx** [comment]
May you confirm or not whether you got it working please?

**Comment by CharString** [comment]
On 28 September 2016 18:35:24 CEST, Robert Niederreiter <notifications@github.com> wrote:
>May you confirm or not whether you got it working please?

I don't know how to combine the information in the test with the admin interface. Or does it require a change in the product code? 
-- 
Chris Wesseling
Centrum Wiskunde & Informatica (CWI)
https://www.cwi.nl/people/ccw

**Comment by CharString** [comment]
1.5.1 solved this issue for me.
