### ISSUE TITLE
Remove dependency on yafowil

### ISSUE THREAD

**Issue by hvelarde** [collective/pas.plugins.ldap#23]
IIRC, in Plone 4 we already have 2 form widget libraries; why do you want to have "yet another" one?

**Comment by rnixx** [comment]
It's done as it's done.

**Comment by jensens** [comment]
Well, we wrote it, we decided to use it. And yafowil is so much less painful than z3cform. It is not immersive in any way. And there are no such widgets, as we used, in z3c.
