### ISSUE TITLE
Installing and uninstalling in Plone is confusing

### ISSUE THREAD

**Issue by hvelarde** [collective/pas.plugins.ldap#24]
In the control panel configlet you have:
- LDAP Plugin for PAS - Zope 2 Base Installation 1.5b1
- LDAP/ Active Directory Support

the earlier must be hidden and the uninstallation process of the later must uninstall the earlier also.

**Comment by rnixx** [comment]
Fixed in master

![install_addons_pas_plugins_ldap](https://cloud.githubusercontent.com/assets/246021/21285620/b7738ec0-c43d-11e6-896e-4731af93612b.png)
