### ISSUE TITLE
Uninstall leaves the PAS plugin behind

### ISSUE THREAD

**Issue by hvelarde** [collective/pas.plugins.ldap#25]
![selection_073](https://cloud.githubusercontent.com/assets/341393/18917215/80b37b34-856d-11e6-9824-27c27b49ab46.png)

You'll see the following in your instance event log:

```
2016-09-28 11:15:53 WARNING pas.plugins.ldap LDAPError in authenticateCredentials -> {'desc': "Can't contact LDAP server"}
```

The workaround is to remove the PAS plugin from the ZMI.

**Comment by hvelarde** [comment]
I was trying to add tests to demonstrate the issue but you have a non-standard test setup in this package and I don't know how to do it; any guidance is appreciated.

**Comment by jensens** [comment]
Overall yes, this is an issue.

**Comment by jensens** [comment]
Btw, I left the plugin intentionally behind. Otherwise its settings are vanished. And since people like to click in Add-Ons control-panel on uninstall/ install, because they believe it would fix something, this is probably a good idea.

We may want to disable the plugin in plugin registry on uninstall and enable it there if it is already there.

**Comment by rnixx** [comment]
I updated the todo list in #36

**Comment by hvelarde** [comment]
@jensens I think that's not a good idea (but that's only what I think): all add-ons remove their configuration on uninstall and we must keep consistency.

**Comment by rnixx** [comment]
In a perfect world some has a GS profile with LDAP config stored.
In real world we have all but the perfect world. LDAP configuration can be tricky, thus I think it's a good idea to keep but disable the Plugin on a thoughtlessly triggered Uninstall

**Comment by hvelarde** [comment]
I'm totally fine with your rationale, just don't forget to document that on the README file, please.

**Comment by jensens** [comment]
Go to ZMI and remove the plugin before.

**Comment by hvelarde** [comment]
so that also needs to be documented in the README file; now you understand why I want to discuss every issue on a separate basis: not because I want to bug you, guys, but because I want us to have the best quality on our software.

@rnixx I'm sorry for any misunderstanding.
