### ISSUE TITLE
release 1.5 final

### ISSUE THREAD

**Issue by thet** [collective/pas.plugins.ldap#26]
any reason to not release 1.5 final? people want to use it... https://community.plone.org/t/using-ldap-with-plone-5/1262/29
/cc @jensens

**Comment by jensens** [comment]
I am ok with a final.


Am 6. Oktober 2016 3:30:22 vorm. schrieb Johannes Raggam 
<notifications@github.com>:

**Comment by rnixx** [comment]
done
