### ISSUE TITLE
Connection Test may give ERROR: LDAP users; {'desc': 'Size limit exceeded'}

### ISSUE THREAD

**Issue by datakurre** [collective/pas.plugins.ldap#27]
When the LDAP directory is big enough to require paging.

That seems to be, because node.ext.ldap has API not always passing page_size for LDAP searches.

I don't know yet, if that really affects the use of pas.plugins.ldap. Should know early next week.

**Comment by datakurre** [comment]
It seems that calls through PAS have page_size passed, so this errors only occurs on connection test (when configuring PAS plugin).

**Comment by jensens** [comment]
Good catch, connection should pass page_size as well.

**Comment by jensens** [comment]
Also ldap explorer should pass it (need to check).

**Comment by rnixx** [comment]
page_size setting should be properly set with a default of 1000. @datakurre Has your LDAP server a lower limit?

**Comment by rnixx** [comment]
well, it looks like this search also needs page size passed https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/ugm/_api.py#L499

**Comment by datakurre** [comment]
@rnixx page_size 1000 is good default, but is not passed for search in connection test.

Now that I got pas.plugins.ldap configured properly, outside connection test thing seem to work. I have some issues with group memberships, but I continue to figure out those tomorrow.

**Comment by rnixx** [comment]
fixed via https://github.com/bluedynamics/node.ext.ldap/pull/15
