### ISSUE TITLE
LDAP Settings (ZMI) may save float as Maximum Page Size

### ISSUE THREAD

**Issue by datakurre** [collective/pas.plugins.ldap#28]
I was trying out pas.plugins.ldap and was getting weird exceptions, because page size setting was float instead of int. Not sure, how that came to be, and I'll update the issue when I can reproduce. I was unable to fix that from LDAP Settings (ZMI) form, so I simply added int casting into properties.py.

If I see that again, I'll do a pull.

**Comment by jensens** [comment]
thanks, indeed a bug. fixed in 0d7b061948027f1cb6e8a7ba1c99780b41c19459

**Comment by datakurre** [comment]
Thanks.
