### ISSUE TITLE
pas.plugins.ldap errors in buildout, and fails on startup. Fresh Plone 5.0.6

### ISSUE THREAD

**Issue by merpdotcom** [collective/pas.plugins.ldap#32]
Tried this first with a running system, but could not figure out what was wrong. So setup a fresh install, and same errors during buildout and startup, with no other products added.
Running on OpenSuse 13.2 (if that matters).

After buildout, server can't fully start, so can't use add-on at all. Is there a fix?

Snippets of builout output: https://ghostbin.com/paste/kfr79
And startup error: https://ghostbin.com/paste/s5kz7

Suggestions? 
Thanks!

**Comment by merpdotcom** [comment]
I performed a completely fresh install of 5.0.6 using Unified Installer on OpenSuse 13.2.
Verified it worked correctly.
Then only added pas.plugins.ldap under eggs.
Ran buildout (see output), then attempted to stop instance (errors). Have to remove pas.plugins.ldap, re-rerun buildout, then can stop instance, and start instance.

Even if run buildout with pas.plugins.ldap added, without the instance running, when attempt to start, still get the startup error, and can't fully start Plone (zeoserver starts, but clients do not).

Output includes running manually, and client1 in fg mode.

Here is detailed log of startup, buildout errors, etc.
http://techtalkhawke.com/news/pas-plugins-ldap-on-plone-5-0.6

Suggestions?
Thanks!

**Comment by jensens** [comment]
odict release egg has permission problems. I'll release a odict 1.5.2 soon. So long you can take chmod to fix temporary yourself.

**Comment by jensens** [comment]
https://pypi.python.org/pypi/odict/1.5.2

**Comment by merpdotcom** [comment]
Yes, pinning odict to 1.5.2, fixed that error, unfortunately there were several other products pulled with the same issue, as detailed here: https://community.plone.org/t/pas-plugins-ldap-errors-in-buildout-then-cant-start-plone-fresh-plone-5-0-6-opensuse-13-2/3078/9

To summarize, the other add-ons that had similar permission issues were:

- node-0.9.16 
- node.ext.ugm-0.9.8
- plumber-1.3.1

Manually chmod-ing those resolved the problem. But this has recurred with fresh install each time.
Cheers!

**Comment by rnixx** [comment]
node, node.ext.ugm and plumber should also get permission fix releases
