### ISSUE TITLE
Should pas.plugins.ldap really load all LDAP user "keys" for every request?

### ISSUE THREAD

**Issue by datakurre** [collective/pas.plugins.ldap#4]
Hi, am I missing something here?

All the plugin methods seem to invoke ``self.users``, which is only cached per request, and ends up initializing something called ``Ugm``, e.g.:

https://github.com/collective/pas.plugins.ldap/blob/master/src/pas/plugins/ldap/plugin.py#L185

Initializing ``Ugm``-object eventually calls ``context._load_keys`` in

https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/ugm/_api.py#L442

and that triggers non-paged search for all the available users at

https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/_node.py#L599

And once I paged that search, it took about 15+ seconds for our 90 000 principals. Per request.

What am I missing? Should ``context._load_keys`` really load _all_ the available users, or have we just managed to misconfigure the plugin somehow?

Thanks!

**Comment by rnixx** [comment]
hannes just did some work on caching the UGM tree in RAM instead of building it for each request, which speeds up the whole story a lot. Nevertheless it does not solve the underlying problem of loading all keys for a search base in node.ext.ldap. This refactoring still misses a project/budget

**Comment by thet** [comment]
users/groups caching implemented here: https://github.com/collective/pas.plugins.ldap/pull/13
still, the first call is expensive

**Comment by tdesvenain** [comment]
Lol) NN

**Comment by rnixx** [comment]
@tdesvenain hm?

**Comment by rnixx** [comment]
The underlying problem of loading all keys is basically solved in https://github.com/bluedynamics/node.ext.ldap/tree/performance. It's not completely finished yet, but some might have time and motivation creating also a performance branch of p.p.ldap and start playing around with the new node.ext.ldap branch.

cheers

**Comment by rnixx** [comment]
^^ @chaoflow @pilz @thet @datakurre @tdesvenain @saily

**Comment by pilz** [comment]
@rnixx thanks, very neat!! Will soon look into that!

**Comment by jensens** [comment]
i already created a performance branch and at a first look all works using it.
i did not checked user listing related features, i'am sure there is some work left.
but overall it works much better, even w/o any caching its fast.

**Comment by rnixx** [comment]
node.ext.ldap 1.0b1 is now released which solves this issue.
