### ISSUE TITLE
"Plugin does not implement IGroupManagement" when switching to ActiveDirectory

### ISSUE THREAD

**Issue by fulv** [collective/pas.plugins.ldap#44]
I have inherited a site that has been using plone.app.ldap for years.  Now they want to switch to Active Directory from the `@@ldap-controlpanel`, and we get the following traceback.  I'm not very familiar with LDAP or with PAS stuff, so any suggestions would be appreciated.

    Traceback (innermost last):
    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module zope.formlib.form, line 868, in __call__
    Module five.formlib.formbase, line 50, in update
    Module zope.formlib.form, line 849, in update
    Module zope.formlib.form, line 640, in success
    Module plone.app.ldap.browser.controlpanel, line 56, in handle_edit_actions
    Module zope.event, line 31, in notify
    Module zope.component.event, line 24, in dispatch
    Module zope.component._api, line 136, in subscribers
    Module zope.component.registry, line 321, in subscribers
    Module zope.interface.adapter, line 585, in subscribers
    Module zope.component.event, line 32, in objectEventNotify
    Module zope.component._api, line 136, in subscribers
    Module zope.component.registry, line 321, in subscribers
    Module zope.interface.adapter, line 585, in subscribers
    Module plone.app.ldap.ploneldap.global, line 10, in HandleModified
    Module plone.app.ldap.ploneldap.util, line 43, in guaranteePluginExists
    Module plone.app.ldap.ploneldap.util, line 88, in createLDAPPlugin
    Module plone.app.ldap.ploneldap.util, line 172, in enablePASInterfaces
    Module Products.PluggableAuthService.plugins.BasePlugin, line 98, in manage_activateInterfaces
    Module Products.PluginRegistry.PluginRegistry, line 148, in activatePlugin
    ValueError: Plugin does not implement  <InterfaceClass Products.PlonePAS.interfaces.group.IGroupManagement>

**Comment by rnixx** [comment]
This is pas.plugins.ldap, not plone.app.ldap, different stack

**Comment by jensens** [comment]
@fulv, but you may want to switch to pas.plugins.ldap. AD is supported.

**Comment by fulv** [comment]
Thanks!
