### ISSUE TITLE
bin/buildout not working

### ISSUE THREAD

**Issue by hocinebendou** [collective/pas.plugins.ldap#56]
I'm using `Plone 4.3.11` on `Ubuntu`. I did add `pas.plugins.ldap` to `buildout.cfg`. I get the following error when running `bin/buildout`.

Getting distribution for 'python-ldap'.
file Lib/ldap.py (for module ldap) not found
file Lib/ldap/controls.py (for module ldap.controls) not found
file Lib/ldap/extop.py (for module ldap.extop) not found
file Lib/ldap/ldapobject.py (for module ldap.ldapobject) not found
file Lib/ldap/schema.py (for module ldap.schema) not found
warning: no files found matching 'Makefile'
warning: no files found matching 'Modules/LICENSE'
file Lib/ldap.py (for module ldap) not found
file Lib/ldap/controls.py (for module ldap.controls) not found
file Lib/ldap/extop.py (for module ldap.extop) not found
file Lib/ldap/ldapobject.py (for module ldap.ldapobject) not found
file Lib/ldap/schema.py (for module ldap.schema) not found
file Lib/ldap.py (for module ldap) not found
file Lib/ldap/controls.py (for module ldap.controls) not found
file Lib/ldap/extop.py (for module ldap.extop) not found
file Lib/ldap/ldapobject.py (for module ldap.ldapobject) not found
file Lib/ldap/schema.py (for module ldap.schema) not found
In file included from Modules/LDAPObject.c:8:0:
Modules/errors.h:7:18: fatal error: lber.h: No such file or directory
 #include "lber.h"
                  ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
An error occurred when trying to install python-ldap 2.5.2. Look above this message for any errors that were output by easy_install.
While:
  Installing client1.
  Getting distribution for 'python-ldap'.
Error: Couldn't install: python-ldap 2.5.2

**Comment by jensens** [comment]
Please check if the python ldap build prerequisites are installed, see https://www.python-ldap.org/en/latest/installing.html#build-prerequisites

**Comment by hocinebendou** [comment]
@jensens thanks, the bin/buildout worked perfectly!
