### ISSUE TITLE
yafowil necessary with plone5?

### ISSUE THREAD

**Issue by krissik** [collective/pas.plugins.ldap#57]
Hi all, 
I have plone 5.1rc1installed. On every page load I see yafowils css and javascript loading without being cached:

![yafowil-loading-without-cache](https://user-images.githubusercontent.com/5301889/36413887-7f81215e-1620-11e8-8b88-69dac834ef7f.png)

Because of that https://github.com/collective/pas.plugins.ldap/blob/db74d1e1694d4917299a74b40cd5e3bc2df065d0/src/pas/plugins/ldap/plonecontrolpanel/configure.zcml#L27 
I am wondering if I really need it. Is it save to disable it in resource registry?

Krissi

**Comment by rnixx** [comment]
The p.p.ldap controlpanel form is done with yafowil. The proper way to solve this issue would be to cache the views in https://github.com/bluedynamics/yafowil.plone/blob/master/src/yafowil/plone/resources.py

**Comment by zopyx** [comment]
This relates to 

https://github.com/bluedynamics/yafowil.plone/issues/15

and must be addressed to due the overhead of 0.5-0.7 seconds per request in our case.

**Comment by jensens** [comment]
We wont kick out YAFOWIL unless there are better widgets for `z3c.forms` (good dict and array widgets). 

But we can solve the problem of loading the resources on every request. This is addressed by https://github.com/bluedynamics/yafowil.plone/pull/21

**Comment by jensens** [comment]
Answer is YES. 

Now I can close it here ;)
