### ISSUE TITLE
Automatic Sign out after X Hours

### ISSUE THREAD

**Issue by timhxara** [collective/pas.plugins.ldap#66]
We have been successfully using this LDAP integration with Active Directory for some time now but we are noticing that users are automatically being logged out from Plone after X hours (I believe 2 hours).

This only seems to affect users authenticated with LDAP as local users remain logged in (even when left idle overnight).

Apologies if this has been answered already or is specific to our setup.

**Comment by jensens** [comment]
Cookie lifetime is unrelated to this plugin. Please look at [plone,session](https://github.com/plone/plone.session) for more control about session lifetime.
