### ISSUE TITLE
Error adding user group

### ISSUE THREAD

**Issue by Petchesi-Iulian** [collective/pas.plugins.ldap#84]
I am having an error adding an user group from the Plone UI (/@@usergroup-groupprefs).
Python 3
Plone = 5.2
pas.plugin.ldap = 1.6.2
Products.PluggableAuthService = 2.1.1

> 2019-11-14 10:51:19,993 ERROR   [Zope.SiteErrorLog:251][waitress] 1573728679.9917420.48799933274952845 http://10.110.30.133:12345/Plone/@@usergroup-groupdetails                                                  Traceback (innermost last):                                                                                                                                                                                     
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents                                                                                                                                             
  Module ZPublisher.WSGIPublisher, line 337, in publish_module                                                                                                                                                  
  Module ZPublisher.WSGIPublisher, line 255, in publish   
  Module ZPublisher.mapply, line 85, in mapply                                                                                                                           
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module Products.CMFPlone.controlpanel.browser.usergroups_groupdetails, line 27, in __call__                                                                                                                    
  Module Products.PlonePAS.tools.groups, line 223, in getGroupById           
  Module Products.PlonePAS.pas, line 229, in getGroup
  Module pas.plugins.ldap.plugin, line 675, in getGroupById                                                                                                                                                       
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by alecghica** [comment]
+1

**Comment by jensens** [comment]
thanks for report and fix!
