### ISSUE TITLE
How to update to current version on plone 

### ISSUE THREAD

**Issue by om1221** [collective/pas.plugins.ldap#89]
buildout many times, and upgraded plone to the last version.
But the pas.plugins.ldap = 1.6.1
[versions]
node.ext.ldap = 1.0b9
node.ext.ugm = 0.9.9
pas.plugins.ldap = 1.6.1

**Comment by jensens** [comment]
What is the problem?

**Comment by om1221** [comment]
> What is the problem?

 The last version of pas.plugins.ldap is 1.6.2, isn't it?

**Comment by jensens** [comment]
Yes, for self check just visit https://pypi.org/project/pas.plugins.ldap/#history

**Comment by tkimnguyen** [comment]
if you need help, please ask in our forum https://community.plone.org

**Comment by om1221** [comment]
Thanks
