### ISSUE TITLE
Not support plone5.2 with python3.6？

### ISSUE THREAD

**Issue by om1221** [collective/pas.plugins.ldap#91]
My steps:
1. Clean install Plone 5.2.1, choose python 3.6.
2. Add egg pas.plugins.ldap in buildout.cfg and build it.
3. Start plone and create test site, then enable LDAP/ Active Directory Support.
4. Click LDAP/ AD Support, get error:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 156, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 338, in publish_module
  Module ZPublisher.WSGIPublisher, line 256, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 62, in call_object
  Module zope.browserpage.simpleviewclass, line 41, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 88, in __call__
  Module z3c.pt.pagetemplate, line 173, in render
  Module chameleon.zpt.template, line 306, in render
  Module chameleon.template, line 209, in render
  Module chameleon.utils, line 75, in raise_with_traceback
  Module chameleon.template, line 187, in render
  Module 3c2d53ab5b831827985cfaa888aec91d.py, line 356, in render
  Module fd711e4a8e718a8a01f86bbee890fef7.py, line 286, in render_master
  Module 3ba05ebae63a9af0af9f610a3bcb4043.py, line 687, in render_master
  Module fd711e4a8e718a8a01f86bbee890fef7.py, line 266, in __fill_content
  Module 3ba05ebae63a9af0af9f610a3bcb4043.py, line 1273, in render_content
  Module fd711e4a8e718a8a01f86bbee890fef7.py, line 257, in __fill_main
  Module 3c2d53ab5b831827985cfaa888aec91d.py, line 335, in __fill_prefs_configlet_main
  Module pas.plugins.ldap.properties, line 85, in form
  Module yafowil.yaml.parser, line 23, in parse_from_YAML
  Module yafowil.yaml.parser, line 59, in __call__
  Module yafowil.yaml.parser, line 146, in create_tree
  Module yafowil.yaml.parser, line 122, in call_factory
  Module yafowil.base, line 684, in __call__
KeyError: 'form'

 - Expression: "provider:plone.abovecontent"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 67: col 59)
 - Source:     ... 
                                       ^
 - Expression: "context/@@main_template/macros/master"
 - Filename:   ... oducts/CMFPlone/skins/plone_prefs/prefs_main_template.pt
 - Location:   (line 2: col 30)
 - Source:     ... tal:use-macro="context/@@main_template/macros/master">
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "context/prefs_main_template/macros/master"
 - Filename:   ... 6.egg/pas/plugins/ldap/plonecontrolpanel/controlpanel.pt
 - Location:   (line 6: col 23)
 - Source:     ... l:use-macro="context/prefs_main_template/macros/master"
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  template: <ViewPageTemplateFile - at 0x7f4036d60978>
               options: {...} (0)
               args: <tuple - at 0x7f404cf18048>
               nothing: <NoneType - at 0x9d4380>
               modules: <_SecureModuleImporter - at 0x7f404454c0f0>
               request: <WSGIRequest - at 0x7f4034314ef0>
               view: <SimpleViewClass from /opt/plone/buildout-cache/eggs/pas.plugins.ldap-1.6.2-py3.6.egg/pas/plugins/ldap/plonecontrolpanel/controlpanel.pt plone_ldapcontrolpanel at 0x7f40343e2c88>
               context: <ImplicitAcquisitionWrapper test at 0x7f4039cd7e58>
               views: <ViewMapper - at 0x7f40343a79e8>
               here: <ImplicitAcquisitionWrapper test at 0x7f4039cd7e58>
               container: <ImplicitAcquisitionWrapper test at 0x7f4039cd7e58>
               root: <ImplicitAcquisitionWrapper  at 0x7f403b2d1a20>
               traverse_subpath: <list - at 0x7f403708f888>
               user: <ImplicitAcquisitionWrapper - at 0x7f4039d24678>
               default: <object - at 0x7f404bce4ad0>
               repeat: {...} (0)
               loop: {...} (0)
               wrapped_repeat: <SafeMapping - at 0x7f40366af948>
               target_language: <NoneType - at 0x9d4380>
               translate: <function translate at 0x7f403431e048>
               macroname: master

**Comment by om1221** [comment]
After reinstall plone 5.2.1，and choose /usr/bin/python2.7 this time.
Got the same error: 
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 156, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 338, in publish_module
  Module ZPublisher.WSGIPublisher, line 256, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 62, in call_object
  Module zope.browserpage.simpleviewclass, line 41, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 88, in __call__
  Module z3c.pt.pagetemplate, line 173, in render
  Module chameleon.zpt.template, line 306, in render
  Module chameleon.template, line 209, in render
  Module chameleon.template, line 187, in render
  Module 62a2aa3be6cd469268e6ad5c6789277b.py, line 352, in render
  Module 2b699eeb87c594cf3ad15bbc115df17d.py, line 287, in render_master
  Module b10267ced3ac2104d51be40fbbedda18.py, line 1032, in render_master
  Module 2b699eeb87c594cf3ad15bbc115df17d.py, line 267, in __fill_content
  Module b10267ced3ac2104d51be40fbbedda18.py, line 379, in render_content
  Module 2b699eeb87c594cf3ad15bbc115df17d.py, line 258, in __fill_main
  Module 62a2aa3be6cd469268e6ad5c6789277b.py, line 331, in __fill_prefs_configlet_main
  Module pas.plugins.ldap.properties, line 85, in form
  Module yafowil.yaml.parser, line 23, in parse_from_YAML
  Module yafowil.yaml.parser, line 59, in __call__
  Module yafowil.yaml.parser, line 146, in create_tree
  Module yafowil.yaml.parser, line 122, in call_factory
  Module yafowil.base, line 684, in __call__
KeyError: 'form'

 - Expression: "provider:plone.abovecontent"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 67: col 59)
 - Source:     ... 
                                       ^
 - Expression: "context/@@main_template/macros/master"
 - Filename:   ... oducts/CMFPlone/skins/plone_prefs/prefs_main_template.pt
 - Location:   (line 2: col 30)
 - Source:     ... tal:use-macro="context/@@main_template/macros/master">
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "context/prefs_main_template/macros/master"
 - Filename:   ... 7.egg/pas/plugins/ldap/plonecontrolpanel/controlpanel.pt
 - Location:   (line 6: col 23)
 - Source:     ... l:use-macro="context/prefs_main_template/macros/master"
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fbfb53d80d0>
               views: <ViewMapper - at 0x7fbfb93d1dd0>
               modules: <_SecureModuleImporter - at 0x7fbfc4476950>
               args: <tuple - at 0x7fbfcc6fa050>
               here: <ImplicitAcquisitionWrapper test at 0x7fbfb4d2c7d0>
               wrapped_repeat: <SafeMapping - at 0x7fbfb4d2c870>
               user: <ImplicitAcquisitionWrapper - at 0x7fbfb4e07280>
               nothing: <NoneType - at 0x5569d9260560>
               container: <ImplicitAcquisitionWrapper test at 0x7fbfb4d2c7d0>
               root: <ImplicitAcquisitionWrapper  at 0x7fbfb4d1a190>
               request: <WSGIRequest - at 0x7fbfae755d90>
               traverse_subpath: <list - at 0x7fbfb4d1eaa0>
               default: <object - at 0x7fbfca0d3b90>
               context: <ImplicitAcquisitionWrapper test at 0x7fbfb4d2c7d0>
               view: <SimpleViewClass from /opt/plone/buildout-cache/eggs/pas.plugins.ldap-1.6.2-py2.7.egg/pas/plugins/ldap/plonecontrolpanel/controlpanel.pt plone_ldapcontrolpanel at 0x7fbfae7dc350>
               translate: <function translate at 0x7fbfae763550>
               macroname: master
               options: {...} (0)
               loop: {...} (0)
               target_language: <NoneType - at 0x5569d9260560>

**Comment by ApatheticCosmos** [comment]
I've just installed Plone 5.2.1 and this plugin, and I'm getting exactly the same error.
This is my first time ever working with Plone or Zope, but I think I followed the instructions correctly.
I'm using Python 3.7.

If you figure out what went wrong, please reply here.

**Comment by jensens** [comment]
I now tried with a clone of this repository using Python 3.7 and Plone 5.2-latest (5.2.1), created a fresh site using advanced creation form and checked the LDAP box.
Then I can got to Site-Setup -> Users -> LDAP/AD Support. The form comes up and I can change settings there and save them.

I released the current master branch as 1.7.0, please try with it and come back in case of problems.

**Comment by ApatheticCosmos** [comment]
@jensens I can confirm that this is fixed for me with v1.7.0.
Thanks!

**Comment by om1221** [comment]
Great！Test OK！Thanks a lot ！
